services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=legalflow
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=dev
      - MINIO_ROOT_PASSWORD=devdevdev
    command: server /data --console-address ':9001'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data

volumes:
  pgdata:
  minio:
