services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=legalflow
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=dev
      - MINIO_ROOT_PASSWORD=devdevdev
    command: server /data --console-address ':9001'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data

  web:
    image: node:20-alpine
    working_dir: /app
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./:/app
    command: >
      sh -lc "corepack enable && corepack prepare pnpm@9.11.0 --activate && pnpm install --frozen-lockfile=false && pnpm -F @legalflow/db prisma:generate && pnpm -F @legalflow/web build && pnpm -F @legalflow/web start -w"
    ports:
      - '3000:3000'
    depends_on:
      - postgres

volumes:
  pgdata:
  minio:
